name: Build and Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - run: chmod +x build.sh
      - id: extract_version
        run: |
          VERSION=$(grep '^VERSION=' build.sh | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: timo-builds
          path: |
            build/timo
            build/timo.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: timo-builds
          path: build
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          draft: false
          prerelease: false
          files: |
            build/timo
            build/timo.exe